### ISSUE TITLE
Pretty new to this! why no output pin defined?

### ISSUE THREAD

**Issue by yannickh2** [marcmerlin/AnimatedGIFs#8]
Hey Marc,

just trying out different things with my 16x32 RGB and ESP32. 
With other libraries I had to define my output pin for example Fast LED library.
I have tried with your library to let some simple GIF play but do not know how to configure the code so that the display know from which PIN data comes to the RGB. Maybe I am missing something?

Best regards,
Yannick

**Comment by marcmerlin** [comment]
Sure, all the defines are in 
https://github.com/marcmerlin/AnimatedGIFs/blob/master/neomatrix_config.h
this is so that all your code/demos can include this file, and if you change your hardware, you only have to change one file.

This shows all the hardware backends supported:
https://github.com/marcmerlin/Framebuffer_GFX
this is how I migrated my code from fastled neomatrix to rgbpanels and TFTs without changing any code

Carefully read the comments in neomatrix_config.h, hopefully it should make sense, if not, let me know where you're stuck. Specifically look at the M24BY24 example in the file, and make your own for your own resolution and pin mapping (serial or parallel)
